.TH xfsinvutil 8
.SH NAME
xfsinvutil \- \&xfsdump inventory database checking and pruning utility
.SH SYNOPSIS
.nf
\f3xfsinvutil\f1 [\-F|\-i] [\-m \f2media_label\f1] \-M \f2mount_point\f1 \f2mm/dd/yyyy\f1
\f3xfsinvutil\f1 [\-F|\-i] [\-m \f2media_label\f1] \-u \f2UUID\f1 \f2mm/dd/yyyy\f1
\f3xfsinvutil\f1 [\-F] \-s \f2SESSION_ID\f1
\f3xfsinvutil\f1 \-i
\f3xfsinvutil\f1 \-C
.fi
.SH DESCRIPTION
.I xfsdump 
maintains an online dump inventory in \f2/var/lib/xfsdump/inventory\f1.
The
.B \-I
option of xfsdump displays the inventory contents hierarchically.
The levels of the hierarchy are:
filesystem,
dump session,
stream, and
media file.
.P
.I xfsinvutil 
is a utility to check this inventory database for consistency,
to remove entries of dump sessions which may no longer be of
relevance, and to browse the contents of the inventory.
.P
The following command line options are available:
.TP 5
\f3\-F\f1
Don't prompt the operator.  When
.I xfsinvutil
encounters a matching dump session,
.I xfsinvutil
will normally ask the operator for permission to delete the
entry. With this option the deletion is performed, no questions asked.
.TP 5
\f3\-i\f1
Interactive mode.  Causes
.I xfsinvutil
to run in a mode that will allow the operator to browse and modify the
contents of the inventory. Please refer to the
.B "Interactive Mode"
section below for more information.
.TP 5
\f3\-M\f1 \f2mount_point mm/dd/yyyy\f1
Prunes dump sessions identified by the given mount point which were
created prior to the specified date. Optionally \f3\-m\f1 may be
be specified to further limit the matching dump sessions by media
label.
.I xfsinvutil
will prompt the operator prior to pruning a dump session unless
the \f3\-F\f1 or \f3\-i\f1 options are given.
.TP 5
\f3\-u\f1 \f2UUID mm/dd/yyyy\f1
Like \f3\-M\f1, except the matching filesystem is specified
using its universally unique identifier (UUID) instead of its mount point.
.TP 5
\f3\-m\f1 \f2media_label\f1
If specified, only sessions with at least one media file whose label
matches this value will be eligible for pruning.  This restriction is
in addition to those imposed by the date and the \f3\-M\f1 or
\f3\-u\f1 options.  This option allows the pruning of all inventory
references to media which may have been overwritten or lost. Note that
this option does not apply to sessions with no media files.
.TP 5
\f3\-s\f1 \f2SESSION_ID\f1
Prunes the dump session identified by the given session id.
.I xfsinvutil
will prompt the operator prior to pruning a dump session unless
the \f3\-F\f1 option is given.
.TP 5
.B \-C
With this option, 
.I xfsinvutil 
performs consistency checks for all entries in the inventory database.
It fixes any problems found. If no consistent entries are found , the
corresponding inventory database file is removed.
.SS Interactive Mode
When run with \f3-i\f1,
.I xfsinvutil
will present the operator with a hierarchical representation of the
.I xfsdump
inventory.  In this mode, the operator can use the arrow keys (or
the 
.B h
.B j
.B k
.B l
keys)
to navigate the inventory and also use the following keys and
functionality:
.TP 5
\f3+\f1
Expand a branch of the tree.
.TP 5
\f3-\f1
Collapse a branch of the tree.
.TP 5
\f3*\f1
Fully expand a branch of the tree.
.TP 5
\f3%\f1
Fully collapse a branch of the tree.
.TP 5
\f3h\f1
Move selection to the parent entry.
.TP 5
\f3l\f1
Move selection to the child entry.
.TP 5
\f3j\f1
Move selection to next entry.
.TP 5
\f3k\f1
Move selection to previous entry.
.TP 5
\f3d\f1
Mark the current record, and all sub-records, to be deleted.
.TP 5
\f3u\f1
Clear the current record and all parent records from being deleted.
.TP 5
\f3i\f1
Import another
.I xfsdump
inventory.
.TP 5
\f3?\f1
Show help window.
.TP 5
\f3x\f1
Commit any changes made to the inventory, and exit the program.
.TP 5
\f3q\f1
Exit the program without committing any changes to the inventory.
.P
Inventories from other hosts can be imported to create a larger common
inventory.  It is recommended that the contents of 
.I /var/lib/xfsdump/inventory
on the remote host be copied to a temporary local directory prior to
running
.IR xfsinvutil .
When
.I xfsinvutil
is run in interactive mode, and the operator hits
.BR i ,
they will be prompted for the path to the inventory to be imported.
.I xfsinvutil
will then add the contents of the imported inventory to the main
window, and all entries will be marked as imported.  The operator can
then delete any of these entries that are not to be imported.  When the
operator commits the changes,
.I xfsinvutil
will import any entries which were not marked as deleted.  Deleted entries are
not actually deleted from the original imported inventory.
.SH NOTES
.SS Inventory
Each dump session updates an inventory database in \f2/var/lib/xfsdump/inventory\f1.
.I xfsdump
uses the inventory to determine the base of incremental
and resumed dumps.
.P
This database can be displayed by invoking
.I xfsdump
with the
.B \-I
option.
The display uses tabbed indentation to present the inventory
hierarchically.
The first level is filesystem.
The second level is session.
The third level is media stream (currently only one stream is supported).
The fourth level lists the media files sequentially composing the stream.
.SH FILES
.TP 25
/var/lib/xfsdump/inventory
dump inventory database
.SH SEE ALSO
xfsdump(8),
xfsrestore(8).
